#!/usr/bin/env node
/**
 * Turn a lab study into a library effect — the EFFECTS entry, the CMS row, and
 * an honest list of what it could not decide.
 *
 * WHY THIS EXISTS. The deliverable is a Framer library of 100+ buttons; the lab
 * page is its source. Until now the two tracks were inverted: the sealed study
 * modules were generated by one sync-framer.mjs run, and the library — the
 * actual product — was hand-built one effect per afternoon. That is why the
 * page reached 114 studies while the library reached 16. This closes the
 * inversion by pointing the same machinery at the track that matters.
 *
 *   node tools/library.mjs                 # every portable study
 *   node tools/library.mjs --only 07,49    # a subset, by card number
 *   node tools/library.mjs --check         # classify only, write nothing
 *
 * IT DRAFTS; IT DOES NOT DECIDE. Everything mechanical is exact and is done:
 * scoping, the timing ladder, the easings, the treatment split, the layer
 * count, the CMS row. Everything that needs a human is NAMED rather than
 * guessed, because the one thing a generator must not do on this page is emit
 * something plausible and wrong. See «What it will not decide» below.
 *
 * Nothing here touches Framer. It writes files for review, and the port is
 * still a person pasting a reviewed block.
 */
import fs from 'node:fs'
import http from 'node:http'
import path from 'node:path'
import { spawn } from 'node:child_process'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const INDEX = path.join(ROOT, 'index.html')
const OUT = path.join(ROOT, 'build', 'library')
const args = process.argv.slice(2)
const CHECK = args.includes('--check')
const ONLY = args.includes('--only')
  ? args[args.indexOf('--only') + 1].split(',').map(s => s.trim())
  : null
const say = (...m) => console.error('·', ...m)

/* ---- the translation table -------------------------------------------- *
 * The timing ladder is EXACT and that is checkable, not assumed. Inside
 * `.btn` the lab runs 83/133/200/300 at rest and 133/200/300/450 on hover
 * (index.html, «.btn{ --t-2:83ms … }»). HoverEffect's BASE declares the same
 * four pairs under momo names. So each lab rung has one momo rung with the
 * same two values, and a translated effect keeps the lab's timing rather than
 * approximating it.
 *
 * --t-1 is not redeclared inside .btn, so it is a flat 83ms — the press rung.
 * --d-2 is the one INEXACT row: a flat 100ms against --momo-delay's 50→100.
 * It is mapped and flagged, never silently equated.                        */
const TIME = {
  '--t-5': '--momo-t-in',     // 300 → 450
  '--t-4': '--momo-t-mid',    // 200 → 300
  '--t-3': '--momo-t-sm',     // 133 → 200
  '--t-2': '--momo-t-label',  //  83 → 133
  '--t-1': '--momo-t-press',  //  83 flat
  '--d-1': '--momo-delay',    //  50 → 100
}
const INEXACT = { '--d-2': ['--momo-delay', 'flat 100ms in the lab; --momo-delay is 50→100'] }

/* The two easings HoverEffect already holds as constants. Emitted as ${QUINT}
 * / ${OUT} so the generated block reads like the hand-written ones and stays
 * one edit away from the file's own vocabulary. */
const EASE = { '--e-quint': '${QUINT}', '--e-out': '${OUT}' }

/* Colour is the dangerous half. `Hover` is THE ARRIVING COLOUR and the label
 * flip does NOT follow it — that has been got wrong before. Only these three
 * are mapped; every other colour token is left as its resolved literal and
 * reported, so a wrong colour is visible in the diff instead of shipped. */
const COLOUR = {
  '--ink-hover': 'var(--momo-hover, var(--momo-fill))',
  '--on-ink-hover': 'var(--momo-on-fill)',
  '--ink': 'currentcolor',
}

/* ---- 1. harvest -------------------------------------------------------- */
// The copy button is the only generator (R3). Clicking it with Option held
// yields the sealed component — the same bytes a visitor gets — so the library
// and the page can never describe different CSS.
function findChrome () {
  if (process.env.CHROME) return process.env.CHROME
  const cache = path.join(process.env.HOME, 'Library/Caches/ms-playwright')
  const shells = fs.existsSync(cache)
    ? fs.readdirSync(cache).filter(d => d.startsWith('chromium_headless_shell-')).sort().reverse()
    : []
  for (const d of shells) {
    for (const arch of ['mac-arm64', 'mac-x64', 'linux64']) {
      const p = path.join(cache, d, `chrome-headless-shell-${arch}`, 'chrome-headless-shell')
      if (fs.existsSync(p)) return p
    }
  }
  const chrome = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
  if (fs.existsSync(chrome)) return chrome
  throw new Error('no Chrome found; set CHROME=<path>')
}

async function harvest () {
  const server = http.createServer((rq, rs) => {
    const u = rq.url.split('?')[0]
    const f = path.join(ROOT, u === '/' ? 'index.html' : u)
    fs.readFile(f, (e, d) => {
      if (e) { rs.writeHead(404); rs.end('nf'); return }
      rs.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' })
      rs.end(d)
    })
  })
  await new Promise(r => server.listen(0, r))
  const port = server.address().port
  const profile = fs.mkdtempSync('/tmp/bhl-lib-')
  const chrome = spawn(findChrome(), [
    '--remote-debugging-port=0', '--headless=new', '--disable-gpu', '--no-first-run',
    `--user-data-dir=${profile}`, 'about:blank'], { stdio: ['ignore', 'ignore', 'pipe'] })
  // The port is written to stderr; reading it beats guessing a free one.
  const cdpPort = await new Promise((res, rej) => {
    let buf = ''
    chrome.stderr.on('data', d => {
      buf += d
      const m = buf.match(/ws:\/\/127\.0\.0\.1:(\d+)/)
      if (m) res(Number(m[1]))
    })
    setTimeout(() => rej(new Error('chrome did not report a debug port')), 20000)
  })
  let target
  for (let i = 0; i < 100 && !target; i++) {
    try {
      const list = await (await fetch(`http://127.0.0.1:${cdpPort}/json/list`)).json()
      target = list.find(t => t.type === 'page' && t.webSocketDebuggerUrl)
    } catch {}
    if (!target) await new Promise(r => setTimeout(r, 150))
  }
  const ws = new WebSocket(target.webSocketDebuggerUrl)
  await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej })
  let id = 0
  const waits = new Map()
  ws.onmessage = e => {
    const m = JSON.parse(e.data)
    if (m.id && waits.has(m.id)) { waits.get(m.id)(m); waits.delete(m.id) }
  }
  const send = (method, params = {}) =>
    new Promise(r => { const i = ++id; waits.set(i, r); ws.send(JSON.stringify({ id: i, method, params })) })
  const evalJs = async expression => {
    const r = await send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true })
    if (r.result?.exceptionDetails) throw new Error(r.result.exceptionDetails.exception?.description)
    return r.result?.result?.value
  }
  await send('Runtime.enable'); await send('Page.enable')
  await send('Page.navigate', { url: `http://127.0.0.1:${port}/` })
  await new Promise(r => setTimeout(r, 3000))   // the linked token sheet has to land

  await evalJs(`(() => {
    const cap = { v: null }
    const stub = { writeText: t => { cap.v = t; return Promise.resolve() } }
    try { Object.defineProperty(navigator, 'clipboard', { value: stub, configurable: true }) }
    catch (e) { navigator.clipboard.writeText = stub.writeText }
    window.__cap = cap
    window.__cards = [...document.querySelectorAll('.spec')].filter(c => c.querySelector('.copy--fr'))
    return window.__cards.length
  })()`)
  const n = await evalJs('window.__cards.length')
  const out = []
  for (let i = 0; i < n; i++) {
    const rec = JSON.parse(await evalJs(`(async () => {
      const card = window.__cards[${i}]
      const num = (card.querySelector('.num') || {}).textContent.trim()
      const name = (card.querySelector('h3') || {}).textContent.replace(num, '').trim()
      const sect = card.closest('.sect')
      const family = sect ? (sect.querySelector('h2') || {}).textContent.trim() : ''
      const chips = [...card.querySelectorAll('.chip')].map(c => c.textContent.trim())
      const label = (card.querySelector('.lbl') || {}).textContent || ''
      const versions = card.getAttribute('data-versions') || ''
      const key = [...(card.querySelector('.btn') || {classList:[]}).classList]
        .filter(c => c !== 'btn' && !c.startsWith('btn--'))[0] || ''
      window.__cap.v = null
      card.querySelector('.copy--fr').dispatchEvent(new MouseEvent('click', { altKey: true }))
      await new Promise(r => setTimeout(r, 0))
      return JSON.stringify({ num, name, family, chips, label, versions, key, code: window.__cap.v })
    })()`))
    if (rec.code) out.push(rec)
  }
  ws.close(); chrome.kill(); server.close()
  await new Promise(r => setTimeout(r, 500))
  try { fs.rmSync(profile, { recursive: true, force: true }) } catch {}
  return out
}

/* ---- 2. translate ------------------------------------------------------ */
// The sealed file marks its own sections with block comments. The effect block
// is the last of them and runs to the closing backtick of the CSS literal.
function effectBlock (code) {
  const at = code.indexOf('/* the effect */')
  if (at < 0) return null
  const end = code.indexOf('\n`', at)
  return code.slice(at + '/* the effect */'.length, end < 0 ? undefined : end).trim()
}

// Values the sealed file resolved for us, so a token the map does not know can
// still be emitted as the literal the lab actually renders.
function tokenValues (code) {
  const vals = {}
  const re = /(--[\w-]+)\s*:\s*([^;{}]+)[;}]/g
  let m
  while ((m = re.exec(code))) if (!vals[m[1]]) vals[m[1]] = m[2].trim()
  return vals
}

function translate (rec) {
  const flags = []
  let css = effectBlock(rec.code)
  if (!css) return { skip: 'the sealed component has no effect block', flags }
  const vals = tokenValues(rec.code)

  // Treatment rules are a separate record in HoverEffect, so they come out of
  // the main block rather than being scoped into it.
  const treatments = {}
  css = css.split('\n').filter(line => {
    const m = line.match(/\.bhl-btn--(solid|line|text)\b/)
    if (!m) return true
    const t = { solid: 'filled', line: 'outline', text: 'link' }[m[1]]
    ;(treatments[t] ||= []).push(line.replace(/\.[\w-]+\.bhl-btn--(solid|line|text)/g, '.momo-fx'))
    return false
  }).join('\n')

  // The effect's own class becomes .momo-fx. It is the first class in the
  // block and it is the card's key, so this cannot catch a house class.
  if (!rec.key) return { skip: 'no effect class on the button', flags }
  const keyRe = new RegExp('\\.' + rec.key.replace(/-/g, '\\-') + '(?![\\w-])', 'g')
  css = css.replace(keyRe, '.momo-fx')

  // The lab qualifies the effect class with the button base class. There is no
  // .bhl-btn in a Framer frame, so `.bhl-btn.momo-fx` matches nothing at all —
  // the effect would arrive looking like it had simply failed. Compounded, the
  // base class carries no meaning the .momo-fx does not already carry, so it
  // comes off. Left BARE it means something else entirely: a rule reaching for
  // a sibling button, which is a row effect, caught below.
  css = css.replace(/\.bhl-btn(?![\w-])\.momo-fx/g, '.momo-fx')
           .replace(/\.momo-fx\.bhl-btn(?![\w-])/g, '.momo-fx')

  // The lab wraps every hover in a (hover:hover) query and states the
  // focus-visible twin separately. HoverEffect's house form is one rule naming
  // both, which is what its BASE and every hand-written entry already do.
  css = css.replace(/@media \(hover: hover\) and \(pointer: fine\)\{([^}]*\})\}/g, '$1')

  // A full-bleed pseudo-element sits ON TOP of the frame's own content, so in
  // Framer it swallows the click that the frame is there to receive. The lab
  // never noticed because its plate is inside a real <button> whose label is a
  // sibling; a Framer frame is the click target itself. Every hand-written
  // entry carries this, and it is unconditional rather than a judgement.
  //
  // It runs BEFORE the easing substitution on purpose: ${QUINT} carries a
  // closing brace, so a declaration regex run afterwards ends the block early
  // and writes the property inside the transition value.
  css = css.replace(/(::(?:before|after)[^{]*\{)([^}]*)\}/g, (m, head, decls) =>
    /position:\s*absolute/.test(decls) && !/pointer-events/.test(decls)
      ? `${head}${decls.replace(/;?\s*$/, '')}; pointer-events: none; }`
      : m)

  // Timing and easing: exact, one rung to one rung.
  for (const [lab, momo] of Object.entries(TIME))
    css = css.replaceAll(`var(${lab})`, `var(${momo})`)
  for (const [lab, konst] of Object.entries(EASE))
    css = css.replaceAll(`var(${lab})`, konst)
  for (const [lab, [momo, why]] of Object.entries(INEXACT))
    if (css.includes(`var(${lab})`)) {
      css = css.replaceAll(`var(${lab})`, `var(${momo})`)
      flags.push(`timing ${lab} → ${momo} is INEXACT — ${why}. Check the delay reads right.`)
    }
  for (const [lab, momo] of Object.entries(COLOUR))
    css = css.replaceAll(`var(${lab})`, momo)

  // Anything still unresolved is a token this tool has no opinion about. It is
  // emitted as the literal the lab renders and reported, rather than left as a
  // var() that resolves to nothing inside a Framer frame.
  // The token name is captured up to its own delimiter. A negative lookahead
  // after a greedy class lets the engine backtrack one character to satisfy
  // itself, which silently reports `--pair-gap` as `--pair-ga` and then fails
  // to substitute it — so the delimiter is matched rather than merely asserted.
  const left = [...css.matchAll(/var\((--[\w-]+)\s*([,)])/g)]
    .filter(m => m[2] === ')')     // a var() WITH a fallback already has an answer
    .map(m => m[1])
  for (const t of new Set(left)) {
    if (t.startsWith('--momo')) continue
    if (vals[t]) {
      css = css.replaceAll(`var(${t})`, vals[t])
      flags.push(`token ${t} inlined as ${vals[t]} — no momo equivalent; check it should not be a control`)
    } else {
      flags.push(`token ${t} is UNRESOLVED — the sealed file does not carry a value for it`)
    }
  }

  // The sealed component ships its own token layer, scoped and prefixed --bhl-,
  // and every reference carries the literal as a fallback. HoverEffect has no
  // token layer at all, so the var() would resolve to its fallback on every
  // load and the indirection buys nothing — it is collapsed to the literal.
  // A COLOUR collapsed this way is still reported: it may want to be one of the
  // momo properties instead, and that is the arriving-colour judgement this
  // tool refuses to make on its own.
  // One level of nesting in the fallback, because the literals include
  // cubic-bezier(...) and rgba(...) — a flat [^()] class stops at their
  // opening paren and leaves the reference behind.
  css = css.replace(/var\(--bhl-([\w-]+),\s*((?:[^()]|\([^()]*\))*)\)/g, (m, name, lit) => {
    if (/ink|accent|fill|bg|line|on-/.test(name))
      flags.push(`colour --bhl-${name} collapsed to ${lit.trim()} — decide whether it should be `
               + `var(--momo-hover), var(--momo-fill) or var(--momo-on-fill)`)
    return lit.trim()
  })

  // The label. In the lab it is `.lbl`; in Framer it is whatever text layer the
  // user put in the frame, so a rule that only recolours it is already covered
  // by BASE + FLIP and is dropped. `position: relative` and `z-index` count as
  // covered too — BASE states both on `> *` — which is what stops a dead
  // `.bhl-lbl` selector being emitted into a file where nothing matches it.
  // A rule that MOVES the label cannot be, and is reported rather than guessed.
  let flip = false
  css = css.split('\n').filter(line => {
    if (!/\.bhl-lbl\b/.test(line)) return true
    const decls = (line.match(/\{([^}]*)\}/) || [, ''])[1]
    const covered = decls.split(';').filter(d => d.trim()).every(d =>
      /^\s*(color|transition|transition-delay)\s*:/.test(d) ||
      /^\s*position\s*:\s*relative\s*$/.test(d) ||
      /^\s*z-index\s*:/.test(d))
    if (covered) { flip = /color\s*:/.test(decls) || flip; return false }
    flags.push(`the label rule «${line.trim().slice(0, 70)}…» does more than recolour — `
             + `in Framer the label is a child text layer, so this needs targeting by hand`)
    return true
  }).join('\n')

  // Extra elements the effect draws. HoverEffect appends <i data-momo-layer>
  // nodes, so a ::before/::after pair is free but a real child element is not.
  const layers = (css.match(/>\s*i\b|\[data-momo-layer/g) || []).length
  const svg = /<svg|\bcurrentColor\b.*<path/i.test(rec.code) && /\.bhl-ico|<svg/.test(rec.code)
  if (svg) flags.push('the demo carries an inline <svg> — HoverEffect can only add empty <i> layers, '
                    + 'so this effect is NOT portable as-is')
  const js = rec.chips.some(c => /\bJS\b/.test(c))
  if (js) flags.push('the study needs JavaScript — HoverEffect injects CSS only, so this is NOT portable as-is')

  // What is left of the token layer points at the LINKED Graphite sheet —
  // `var(--bhl-bg, var(--bg-0))` — and inside a Framer frame neither name is
  // defined. A custom property that resolves to nothing makes the whole
  // declaration invalid, so the property silently drops and the effect arrives
  // subtly wrong rather than visibly broken. That is the failure mode this
  // page exists to avoid, so it blocks.
  const dangling = [...new Set([...css.matchAll(/var\(--bhl-([\w-]+),\s*var\(/g)].map(m => m[1]))]
  if (dangling.length) flags.push(`\`--bhl-${dangling.join(', --bhl-')}\` fall back to the linked Graphite `
                    + 'sheet, which a Framer frame does not have — the declaration would drop silently. '
                    + 'Give each one a literal or a momo property.')

  // A bare .bhl-btn survived the compound strip, so this effect reasons about
  // more than one button — a row, a pair, a segmented group. HoverEffect is
  // dropped INSIDE one frame and can only ever see that frame.
  const row = /\.bhl-btn(?![\w-])/.test(css)
  if (row) flags.push('the effect reaches for a sibling button — it is a row or pair, and HoverEffect '
                    + 'lives inside a single frame, so this is NOT portable as-is')

  // A child element of the lab's own markup that Framer has no counterpart for.
  const orphan = [...new Set([...css.matchAll(/\.bhl-([\w-]+)/g)].map(m => m[1]))]
  if (orphan.length) flags.push(`the effect styles the lab's own \`${orphan.join(', ')}\` element(s), `
                    + 'which do not exist inside a Framer frame — NOT portable as-is')

  // Charter rule 1: the frame's fill, radius and padding stay the user's. An
  // effect whose REST rule paints the frame's own background or border is
  // imposing a surface, and would arrive stamping the lab's dark palette onto
  // somebody's button. Reported rather than dropped, because for a few of
  // these the surface IS the effect and the answer is a treatment block.
  const imposes = /\.momo-fx\s*\{[^}]*?\b(background|border)\s*:/.test(css)
  if (imposes) flags.push('the rest rule paints the frame\'s own background or border — the Framer frame '
                    + 'owns its surface (charter rule 1), so this needs a treatment block or a rethink')

  const portable = !svg && !js && !row && !orphan.length && !imposes && !dangling.length
  return { css: css.trim(), treatments, flip, layers, flags, portable }
}

/* ---- 3. emit ----------------------------------------------------------- */
const ts = s => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`')

const studies = await harvest()
say(`harvested ${studies.length} studies`)
const picked = ONLY ? studies.filter(s => ONLY.includes(s.num)) : studies
if (ONLY && picked.length !== ONLY.length)
  say(`warning: asked for ${ONLY.length}, matched ${picked.length}`)

const done = [], blocked = []
for (const rec of picked) {
  const t = translate(rec)
  if (t.skip) { blocked.push({ ...rec, why: [t.skip] }); continue }
  ;(t.portable ? done : blocked).push({ ...rec, ...t, why: t.flags })
}
say(`${done.length} portable · ${blocked.length} need a decision`)

if (CHECK) {
  for (const b of blocked) console.log(`${b.num} ${b.name}\n    ${(b.why || []).join('\n    ')}`)
  process.exit(0)
}

fs.mkdirSync(OUT, { recursive: true })
const effects = done.map(d =>
  `    /* ${d.num} — ${d.name} */\n    ${d.key.replace(/-/g, '')}: \`\n${ts(d.css)}\`${d.flip ? ' + FLIP' : ''},`
).join('\n\n')
fs.writeFileSync(path.join(OUT, 'EFFECTS.ts'),
  `/* Generated by tools/library.mjs — review before merging into HoverEffect.tsx.\n`
+ `   ${done.length} entries. Each one is scoped to .momo-fx, on the momo timing\n`
+ `   ladder, with treatments split out. Read REPORT.md first. */\n\n${effects}\n`)

fs.writeFileSync(path.join(OUT, 'TITLES.ts'),
  done.map(d => `    ${d.key.replace(/-/g, '')}: "${d.num} · ${d.name}",`).join('\n') + '\n')

const layers = done.filter(d => d.layers > 0)
fs.writeFileSync(path.join(OUT, 'LAYERS.ts'),
  `const LAYERS = { ${layers.map(d => `${d.key.replace(/-/g, '')}: ${d.layers}`).join(', ')} }\n`)

fs.writeFileSync(path.join(OUT, 'effects.cms.json'), JSON.stringify(done.map(d => ({
  Number: d.num, Name: d.name, 'Effect Key': d.key.replace(/-/g, ''),
  Family: d.family, Label: d.label, Versions: d.versions, 'Lab Title': d.name,
})), null, 2))

const report = [
  '# Library port — generated draft', '',
  `${done.length} portable, ${blocked.length} blocked, out of ${picked.length} studies.`, '',
  '**Nothing here is merged.** The mechanical half is exact — scoping, the timing',
  'ladder, the easings, the treatment split. The judgement half is listed below',
  'per effect and is why this is a draft rather than a patch.', '',
  '## Portable, with notes', '',
  ...done.map(d => `- **${d.num} ${d.name}** \`${d.key}\`${d.flags.length ? '\n' + d.flags.map(f => `  - ${f}`).join('\n') : ' — clean'}`),
  '', '## Blocked', '',
  ...blocked.map(b => `- **${b.num} ${b.name}**\n${(b.why || []).map(f => `  - ${f}`).join('\n')}`),
].join('\n')
fs.writeFileSync(path.join(OUT, 'REPORT.md'), report + '\n')

say(`wrote ${path.relative(ROOT, OUT)}/ — EFFECTS.ts, TITLES.ts, LAYERS.ts, effects.cms.json, REPORT.md`)
